# built with Flutter 3.38.5 (Apple M1), Dart 3.10.4, CocoaPods 1.16.2, Xcode 26.2
name: tommylingo
description: Tommylingo Mobile App
version: 1.3.0+11

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  scoped_model: 2.0.0         # state management
  http: 1.6.0                 # http support
  xml: 6.6.1                  # xml parsing
  tuple: 2.0.2                # tuples
  flutter_typeahead: 5.2.0    # text field with suggestions
  shared_preferences: 2.5.4   # key-value storage
  json_annotation: 4.9.0      # parsing json
  spoiler_widget: 1.0.18      # spoiler widget like in Telegram

dev_dependencies:
  build_runner: 2.10.4        # generate json schema, run "flutter pub run build_runner build"
  json_serializable: 6.11.3   # generate json schema
  flutter_launcher_icons: 0.14.4 # icons generator, run: "dart run flutter_launcher_icons"

dependency_overrides:
  win32: 5.5.4                # TMP: error "UnmodifiableUint8ListView not found" (2025-12), probably will be fixed soon

flutter:
  uses-material-design: true

flutter_launcher_icons:
  ios: true
  image_path: "assets/appicon.png"
  macos:
    generate: true
    image_path: "assets/appicon.png"
