# Built with Flutter 3.7.12, CocoaPods 1.11.3
name: tommyannals
description: Tommyannals Mobile App
version: 23.12.12+1
publish_to: 'none' # to prevent publish with 'flutter pub publish'

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  scoped_model: 2.0.0                # state management
  http: 0.13.6                       # http support
  json_annotation: 4.8.1             # json auto-generation
  table_calendar: 3.0.9              # calendar widget
  flutter_typeahead: 4.3.8           # text field with suggestions

dev_dependencies:
  flutter_lints: 2.0.0
  build_runner: 2.3.3                # json auto-generation
  json_serializable: 6.6.2           # json auto-generation

flutter:
  uses-material-design: true
