# built with Flutter 3.38.5 (Mac Apple M1), Dart 3.10.4, CocoaPods 1.16.2, xCode 26.2
name: tommyannals
description: Tommy Annals Mobile App
version: 1.1.0+7

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  scoped_model: 2.0.0                # state management
  http: 1.6.0                        # http support
  json_annotation: 4.9.0             # json auto-generation
  table_calendar: 3.2.0              # calendar widget
  flutter_typeahead: 5.2.0           # text field with suggestions
  flutter_platform_alert: 0.8.0      # native dialogs

dev_dependencies:
  build_runner: 2.10.4               # generate json schema, run "flutter pub run build_runner build"
  json_serializable: 6.11.3          # generate json schema
  flutter_launcher_icons: 0.14.4     # icons generator, run: "dart run flutter_launcher_icons"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  ios: true
  image_path: "assets/appicon.png"
  macos:
    generate: true
    image_path: "assets/appicon.png"
